awslabs/Renate

.github/workflows/pypi_publish.yml
=> PyPI Publish Action

doc/conf.py, doc/requirements.txt, src/renate/data/data_module.py
=> Fixing Doc Conf

doc/getting_started/output.rst
Some leftovers from converting md to rst.
=> Fixing Links in Documentation

examples/simple_classifier_cifar10/renate_config.py, examples/train_mlp_locally/renate_config.py
=> Adjust type hints in example renate_config.py

.readthedocs.yml, README.rst, doc/conf.py, doc/index.rst, doc/requirements.txt, examples/simple_classifier_cifar10/renate_config.py, src/renate/benchmark/datasets/vision_datasets.py, src/renate/benchmark/models/__init__.py, src/renate/benchmark/models/mlp.py, src/renate/benchmark/models/resnet.py, src/renate/benchmark/models/vision_transformer.py, src/renate/data/__init__.py, src/renate/evaluation/evaluator.py, src/renate/memory/__init__.py, src/renate/models/__init__.py, src/renate/tuning/__init__.py, src/renate/updaters/experimental/gdumb.py, src/renate/updaters/learner.py, src/renate/updaters/learner_components/component.py, src/renate/updaters/learner_components/losses.py, test/conftest.py, test/renate/data/test_data_module.py, test/renate/data/test_datasets.py, test/renate/models/test_renate_module.py
- Remove all warnings in doc
- RTD will only update if there are no warnings
- Added typing to reference
- Documentation documents now functions with shorter import name (no change in API)
=> Minor Reference Improvements

.github/workflows/codeql.yml
Add GitHub action for code scanner
=> Add GitHub action for code scanner

examples/simple_classifier_cifar10/start_with_hpo.py, examples/simple_classifier_cifar10/start_without_hpo.py
Fixed the job name in the example to satisfy SM requirements
=> Fixed job name in example to respect SM requirements

doc/requirements.txt
Will fix our doc building and avoid breaking changes in the future.
=> Pin Sphinx Version

.github/dependabot.yml, .github/workflows/run_unit_tests.yml, .github/workflows/test_docs.yml, doc/requirements.txt
Add a test to check if docs are still building and extend dependabots coverage to github actions.
=> Check Docs Are Building on PR

.github/dependabot.yml
We probably want dependency changes merged in dev first.
=> Dependabot Creates PRs for `dev` Branch

.github/workflows/run_unit_tests.yml, examples/train_mlp_locally/start_training_without_hpo.py
Testing if code was formatted with black.
=> Black Check

README.rst
Added the blog link to the readme
=> Added the blog post link to the readme

src/renate/memory/buffer.py, test/renate/memory/test_buffer.py
Allow buffer to store (nested) tuples/dictionaries of tensors
=> Allow buffer to store (nested) tuples/dictionaries of tensors

src/renate/benchmark/experiment_config.py, src/renate/benchmark/scenarios.py, test/renate/benchmark/test_experimentation_config.py, test/renate/benchmark/test_scenarios.py
Adding a scenario splitting a data module into random chunks of equal size.
=> Add IID scenario

doc/getting_started/how_to_renate_config.rst
=> Fix bug in documentation

src/renate/benchmark/scenarios.py, test/renate/benchmark/test_scenarios.py
=> Return `num_tasks` many test datasets in `IIDScenario`

src/renate/benchmark/experiment_config.py, src/renate/benchmark/scenarios.py, test/renate/benchmark/test_experimentation_config.py, test/renate/benchmark/test_scenarios.py
=> Add SoftSortingScenario

doc/getting_started/how_to_run_training.rst
=> Updating documentation after renaming input/output folder

doc/benchmarking/index.rst
Replacing an outdated function name
=> Update outdated function name

src/renate/benchmark/experiment_config.py, src/renate/benchmark/scenarios.py, test/renate/benchmark/test_experimentation_config.py, test/renate/benchmark/test_scenarios.py
Adding `HueShiftScenario` and fixes and refactors `FeatureSortingScenario`.
=> HueShiftScenario and FeatureSortingScenario Fix

examples/simple_classifier_cifar10/start_with_hpo.py, examples/simple_classifier_cifar10/start_without_hpo.py, examples/train_mlp_locally/start_training_with_er_without_hpo.py, examples/train_mlp_locally/start_training_with_hpo.py, examples/train_mlp_locally/start_training_without_hpo.py, src/renate/updaters/learner_components/losses.py, test/renate/evaluation/metrics/test_regression_metrics.py
*Description of changes:* avoid encouraging users to put account-id in code to avoid their id to be leaked by accident
=> Update instructions to avoid users putting account-id in code.

examples/simple_classifier_cifar10/start_with_hpo.py, examples/simple_classifier_cifar10/start_without_hpo.py, examples/train_mlp_locally/start_training_with_er_without_hpo.py, examples/train_mlp_locally/start_training_with_hpo.py, examples/train_mlp_locally/start_training_without_hpo.py, requirements.txt, src/renate/benchmark/experimentation.py, src/renate/cli/parsing_functions.py, src/renate/training/training.py, src/renate/utils/avalanche.py, test/renate/training/test_run_training.py
Bumps syne tune, allows to customize schedulers for experimentation and uses max_resource_attr instead of max_t.
=> Bump Syne Tune

README.rst, doc/getting_started/install.rst, pyproject.toml, requirements.txt, src/renate/cli/parsing_functions.py
I made avalanche an optional dependency. Furthermore, I've added the coverage badge to the README
=> Avalanche is optional

.gitignore, examples/nlp_finetuning/install_env.sh, examples/nlp_finetuning/renate_config.py, examples/nlp_finetuning/start.py, examples/nlp_peft/renate_peft_config.py, examples/nlp_peft/start.py, examples/nlp_peft/test_peft.ipynb, src/renate/cli/parsing_functions.py, src/renate/cli/run_training.py, src/renate/defaults.py, src/renate/training/training.py, src/renate/updaters/experimental/er.py, src/renate/updaters/learner.py, src/renate/updaters/model_updater.py
Adding the ability to do multigpu training by specifying a strategy in run_training_job that is passed down to er.py.
=> Enabling multigpu training on LocalBackend

doc/examples/train_classifier_sagemaker.rst, doc/examples/train_mlp_locally.rst
*Issue #132 *
I added a couple of sentences explaining the role of the scenario and saying that it can be removed when creating real-world applications.
=> Add explanation for the scenario usage in the examples

.github/scripts/build_docs.sh, .github/workflows/test_docs.yml, doc/conf.py, doc/getting_started/how_to_renate_config.rst, doc/requirements.txt, src/renate/__init__.py, src/renate/updaters/avalanche/plugins.py, src/renate/updaters/learner.py
Our doc building action installs Renate[dev] while rtd does not. Therefore, our tests are passing but the docs are not updating anymore. This PR fixes the github action to reflect what rtd is doing and a hotfix addresses the problem.
Closes #196 
=> Fix Doc Building

README.rst
*Issue #198*
Added paper and bibtex to cite the paper
=> Update README.rst with paper ref

doc/examples/index.rst, doc/examples/nlp_finetuning.rst
=> Add doc page explaining NLP example

.github/workflows/integration_tests.yml, src/renate/__init__.py, src/renate/benchmark/experimentation.py, src/renate/defaults.py, src/renate/training/training.py, test/renate/benchmark/test_experimentation.py, test/renate/cli/test_parsing_functions.py, test/renate/renate_config_files/config_scenario.py, test/renate/training/test_run_training.py
Intended purpose is to release a new release for Renate. This PR fixes a bug caused when defining a Renate config file that does not contain any function with an argument `chunk_id`.
=> Minor Release 0.2.1

src/renate/benchmark/datasets/nlp_datasets.py
Closes #232 
Also fixes check whether feature column exists in dataset.
=> Fixes Bug in HuggingFaceTextDataModule

.github/dependabot.yml
Recently, we were missing out on some dependency PRs. After merging this PR, these times will be gone.
=> More PRs by dependabot

src/renate/__init__.py
=> Bump version

requirements.txt, src/renate/benchmark/datasets/wild_time_data.py
wild-time-data was automatically imported causing problems if it wasn't installed.
tensorboard(X) is a dependency we did not have in our requirements file.
=> Missing dependency and problem with import

doc/getting_started/how_to_renate_config.rst, examples/getting_started/renate_config.py, examples/nlp_finetuning/renate_config.py, examples/simple_classifier_cifar10/renate_config.py, examples/train_mlp_locally/renate_config.py, src/renate/benchmark/experiment_config.py, src/renate/benchmark/scenarios.py, src/renate/cli/run_training.py, src/renate/updaters/experimental/er.py, src/renate/updaters/experimental/offline_er.py, src/renate/updaters/learner.py, src/renate/utils/module.py, test/conftest.py, test/integration_tests/configs/suites/quick/offline-er.json, test/renate/benchmark/test_experimentation_config.py, test/renate/models/test_renate_module.py, test/renate/renate_config_files/config.py, test/renate/renate_config_files/config_scenario.py, test/renate/updaters/avalanche/test_avalanche_model_updater.py, test/renate/updaters/experimental/test_joint.py
Loss functions should no longer be reduced.
=> Fix Offline-ER bug and change loss functions

test/integration_tests/configs/scenarios/class-incremental-5updates.json, test/integration_tests/configs/scenarios/feature-sorting-5updates.json, test/integration_tests/configs/scenarios/hue-shift-5updates.json, test/integration_tests/configs/scenarios/iid-5updates.json, test/integration_tests/configs/scenarios/permutation-10updates.json, test/integration_tests/configs/scenarios/rotation-10updates.json, test/integration_tests/configs/suites/main/avalanche-er.json, test/integration_tests/configs/suites/main/avalanche-ewc.json, test/integration_tests/configs/suites/main/avalanche-icarl.json, test/integration_tests/configs/suites/main/avalanche-lwf.json, test/integration_tests/configs/suites/main/cls-er.json, test/integration_tests/configs/suites/main/der.json, test/integration_tests/configs/suites/main/er.json, test/integration_tests/configs/suites/main/gdumb.json, test/integration_tests/configs/suites/main/joint.json, test/integration_tests/configs/suites/main/offline-er.json, test/integration_tests/configs/suites/main/pod-er.json, test/integration_tests/configs/suites/main/rd.json, test/integration_tests/configs/suites/main/super-er.json, test/integration_tests/configs/updaters/rd.json, test/integration_tests/run_experiment.py, test/integration_tests/run_quick_test.py, test/integration_tests/run_test.py
Sharing config files to run longer experiments.
=> Longer Experiments for GPUs

src/renate/data/datasets.py, src/renate/memory/buffer.py, src/renate/memory/storage.py, src/renate/updaters/model_updater.py, test/renate/data/test_datasets.py, test/renate/memory/test_storage.py
=> Implementing a buffer that handles dataset elements of different sizes

README.rst, requirements.txt, src/renate/__init__.py, src/renate/benchmark/datasets/wild_time_data.py
Conflict-free version of #285 
=> Sync dev with main

examples/getting_started/renate_config.py, examples/simple_classifier_cifar10/renate_config.py, examples/train_mlp_locally/renate_config.py, requirements.txt, src/renate/benchmark/experiment_config.py, src/renate/benchmark/experimentation.py, src/renate/cli/parsing_functions.py, src/renate/cli/run_training.py, src/renate/evaluation/metrics/classification.py, src/renate/utils/module.py, test/renate/benchmark/test_experimentation_config.py, test/renate/cli/test_parsing_functions.py, test/renate/renate_config_files/config.py, test/renate/renate_config_files/config_custom_optimizer.py, test/renate/renate_config_files/config_scenario.py, test/renate/updaters/test_model_updater.py
Account for interface changes in torchmetrics 0.11.
=> Upgrade to torchmetrics 0.11

src/renate/updaters/experimental/offline_er.py, test/integration_tests/configs/suites/quick/offline-er.json
=> Fix weighting in OfflineER

src/renate/cli/parsing_functions.py, src/renate/updaters/avalanche/learner.py, src/renate/updaters/avalanche/model_updater.py, test/conftest.py
iCarl is no replay-based method and therefore doesn't have to be a ReplayLearner nor expect its arguments.
=> Cleanup iCarl

benchmarks/run_benchmark.py, doc/benchmarking/renate_benchmarks.rst, src/renate/benchmark/datasets/nlp_datasets.py, src/renate/benchmark/experiment_config.py, src/renate/defaults.py, test/renate/benchmark/test_experimentation_config.py
MultiText dataset in #354 enabled for benchmarking and documented. Some cleanup and bug fixes as well.
Added new argument for benchmarking script that allows to easily change between running Joint with and without reset.
=> MultiText dataset Added to Benchmarking

requirements.txt, src/renate/benchmark/models/transformer.py, test/renate/benchmark/models/test_text_transformer.py
=> Modifies current text transformer implementation to a RenateBenchmarkingModule

src/renate/benchmark/datasets/vision_datasets.py
=> Fixing the issue with Domainnet redownloading

doc/examples/nlp_finetuning.rst
A small improvement to make it easier to find the example
=> Improve title for the NLP example

src/renate/benchmark/datasets/vision_datasets.py
See https://github.com/clear-benchmark/clear-benchmark.github.io/commit/fa2f22e6bcaa47d4512acbcf4ec1643ad9dc66b2
=> CLEAR dataset download link update

test/renate/data/test_data_module.py
A few tests for datasets fail due to modified interfaces etc. This PR fixes those.
=> CLEAR and TinyImageNet tests bugfixes

benchmarks/experiment_configs/datasets/core50.json, benchmarks/experiment_configs/scenarios/core50-ni.json, src/renate/benchmark/datasets/vision_datasets.py, src/renate/benchmark/experiment_config.py, test/renate/benchmark/test_experimentation_config.py
This PR enables the use of CoRe50 dataset. 
=> Core50 dataset
