awslabs/Renate

README.rst

The documentation link at the end or the README file is difficult to find. I added some quicklinks in a very visible position.
It is not great to see them in the landing page of the documentation but we had plans to evolve that page in a different direction anyway.

Improved README with quicklinks at the top

---

src/renate/benchmark/experiment_config.py
src/renate/benchmark/scenarios.py
test/renate/benchmark/test_scenarios.py

Solved issues:
- Number of outputs wasn't forwarded to all architectures
- CI scenario gives useful error message when messing up class_groupings input

Fixing Small Issue in `experiment_config.py`

---

doc/getting_started/supported_algorithms.rst
src/renate/cli/parsing_functions.py
src/renate/updaters/experimental/fine_tuning.py
test/renate/updaters/experimental/test_fine_tuning.py

Add a model updater doing fine-tuning.
This will simplify usage by providing an ad-hoc model updater for the fine-tuning baseline instead of requiring the usage of the SimpleModelUpdater in combination with Learner.

Add finetuning model updater

---

src/renate/benchmark/scenarios.py
src/renate/utils/pytorch.py
test/renate/benchmark/test_scenarios.py

Permutation scenarios had a bug that cause all permutations but first to be the same.
Relaxing sum to 1 check to account for problems with precision.

Permutation Bug Fix

---

src/renate/cli/run_training.py

Right now `deterministic_trainer` is always `True`.

Fix `deterministic_trainer`

---

doc/getting_started/index.rst

Add link to benchmarking in getting started. The lack of visibility of the benchmarking functionalities were brought up my some of the customers testing the library (see https://github.com/awslabs/Renate/issues/130).

Add link to benchmarking in getting started

---

.github/workflows/run_unit_tests.yml
doc/conf.py
doc/requirements.txt
examples/simple_classifier_cifar10/start_with_hpo.py
examples/simple_classifier_cifar10/start_without_hpo.py
examples/train_mlp_locally/start_training_with_er_without_hpo.py
examples/train_mlp_locally/start_training_with_hpo.py
examples/train_mlp_locally/start_training_without_hpo.py
pyproject.toml
src/renate/cli/parsing_functions.py
src/renate/utils/avalanche.py

Some fixes to deal with Sphinx deprecation warning in #99 Attempted to solve earlier in #85 

Bump Sphinx Version

---

.github/scripts/prepend_license.sh
doc/benchmarking/custom_benchmarks.rst
doc/benchmarking/renate_benchmarks.rst
doc/examples/train_classifier_sagemaker.rst
doc/examples/train_mlp_locally.rst
doc/getting_started/how_to_renate_config.rst
doc/getting_started/how_to_run_training.rst
doc/getting_started/supported_algorithms.rst
examples/benchmarking/class_incremental_learning_cifar10_der.py
examples/getting_started/renate_config.py
examples/train_mlp_locally/renate_config.py
examples/train_mlp_locally/start_training_with_er_without_hpo.py
examples/train_mlp_locally/start_training_with_hpo.py
examples/train_mlp_locally/start_training_without_hpo.py
src/renate/benchmark/experiment_config.py
src/renate/cli/parsing_functions.py
src/renate/cli/run_training.py
src/renate/memory/buffer.py
src/renate/memory/storage.py
src/renate/training/training.py
src/renate/updaters/avalanche/plugins.py
src/renate/utils/module.py
test/renate/benchmark/test_experimentation.py
test/renate/benchmark/test_experimentation_config.py
test/renate/cli/test_parsing_functions.py
test/renate/memory/test_storage.py
test/renate/renate_config_files/config.py

Previously, custom arguments had to be of type `str` which required conversion. This PR will allow using types `int`, `float`, `bool`, `tuple`, and `list`.
Documentation was updated to reflect our changes made for custom function arguments.
Addresses #115 

Custom Function Arguments Allow For More Types

---

.github/workflows/integration_tests.yml
.github/workflows/run_renate.yml
.gitignore
test/integration_tests/configs/suites/quick/avalanche-er.json
test/integration_tests/configs/suites/quick/avalanche-ewc.json
test/integration_tests/configs/suites/quick/avalanche-icarl.json
test/integration_tests/configs/suites/quick/avalanche-lwf.json
test/integration_tests/configs/suites/quick/cls-er.json
test/integration_tests/configs/suites/quick/der.json
test/integration_tests/configs/suites/quick/er.json
test/integration_tests/configs/suites/quick/fine-tuning.json
test/integration_tests/configs/suites/quick/gdumb.json
test/integration_tests/configs/suites/quick/joint.json
test/integration_tests/configs/suites/quick/offline-er.json
test/integration_tests/configs/suites/quick/pod-er.json
test/integration_tests/configs/suites/quick/super-er.json
test/integration_tests/run_quick_test.py

*Description of changes:*
Wire up the quick tests to run on GitHub Actions with each PR. 
Observed that the accuracy values differ between Mac and Linux 

add initial integ test workflows

---

doc/getting_started/avalanche.rst
doc/getting_started/index.rst
doc/getting_started/supported_algorithms.rst

Describe Usage of Avalanche updaters and their Limitations

---

doc/benchmarking/custom_benchmarks.rst
doc/benchmarking/renate_benchmarks.rst
doc/getting_started/how_to_renate_config.rst
doc/getting_started/output.rst
examples/nlp_finetuning/renate_config.py
examples/simple_classifier_cifar10/renate_config.py
examples/train_mlp_locally/renate_config.py
src/renate/benchmark/datasets/nlp_datasets.py
src/renate/benchmark/experiment_config.py
src/renate/benchmark/models/transformer.py
src/renate/defaults.py
src/renate/memory/buffer.py
src/renate/training/training.py
test/integration_tests/configs/suites/quick/avalanche-icarl.json
test/integration_tests/run_experiment.py
test/integration_tests/run_quick_test.py
test/renate/benchmark/test_experimentation_config.py
test/renate/data/test_data_module.py

Add RenateModule for Hugging Face transformer and make datasets and transformers available in benchmarking script. Tests are failing for other reasons :(

Add NLP Components to Benchmarking

---

src/renate/memory/buffer.py

This method is no longer used after the recent simplification in checkpointing.

Remove obsolete `set_transforms`  from memory buffer

---

src/renate/benchmark/experimentation.py
src/renate/training/training.py

- Removed source_dir: this requires the entry point to be within source_dir which is not the case for us
- Added dependencies argument: alternate way to upload custom files and folders

Upload custom files and folders with a SageMaker training Job

---

README.rst
requirements.txt
src/renate/__init__.py
src/renate/benchmark/datasets/wild_time_data.py

Sync dev with main

---

.github/workflows/sagemaker_tests.yml
test/integration_tests/generate_requirements.py
test/integration_tests/run_experiment.py
test/integration_tests/run_test.py

Initial PR to run the full test suite from GitHub Actions

Run sagemaker tests from GitHub Actions

---

src/renate/benchmark/experimentation.py
src/renate/defaults.py

Large datasets' buffers can be too big and result in storage issues (noticed while training CLEAR). This flag eliminates backing up intermediate results and overwrites the same folder/files in each update. 

Flag to remove intermediate tasks' states

---

src/renate/benchmark/experimentation.py

`dependencies` was not passed leading to an exception.

Missing Argument Doesn't Allow for Remote Experiments

---

src/renate/benchmark/models/vision_transformer.py
test/renate/benchmark/models/test_vision_transformer.py

Using HuggingFace ViT implementation (#219)

---

doc/benchmarking/index.rst
doc/getting_started/install.rst

In order to run benchmarking, Renate[benchmark] must be installed. This hasn't been described so far.

Describe Installation of Dependencies for Benchmarking

---

src/renate/utils/file.py

Current code loads downloaded file into memory first before writing to disk. This does not work for large files.

Enable Downloading Large Files

---

doc/requirements.txt
pyproject.toml

Latest version of that dependency allows Python versions larger than 3.10, e.g. 3.10.1.

Upgrade wild-time-data package

---

src/renate/updaters/experimental/offline_er.py
src/renate/utils/pytorch.py
test/renate/utils/test_pytorch.py

Offline-ER was expecting torch.Tensors to be returned by the dataloader which is oftentimes not the case, e.g., text data with transformers.

Enable Offline-ER for NestedTensors

---

src/renate/benchmark/experimentation.py
src/renate/evaluation/metrics/classification.py
src/renate/utils/module.py
test/renate/benchmark/test_experimentation.py
test/renate/evaluation/metrics/test_classification.py

Add Micro Average Accuracy

---

src/renate/cli/parsing_functions.py
src/renate/cli/run_training.py
src/renate/updaters/experimental/gdumb.py
src/renate/updaters/experimental/joint.py
test/integration_tests/configs/suites/quick/gdumb.json
test/integration_tests/configs/suites/quick/joint.json
test/renate/updaters/experimental/test_joint.py

Joint and Gdumb reset the models `on_model_update_start`. This results in a non-desired behavior when working with pre-trained models.
There is also no option to *not* reset the model at all.
The change introduces a new flag `reset` which allows to control whether the model will be reset. Furthermore, in case of a reset, the pre-trained model will be reloaded instead of using an untrained model.
The integration tests are expected to break for Joint and GDumb due to a different initialization of the model. Before, the workflow was creating the model and resetting it. Now, it only creates the model without reset.

Support Use of Joint and GDumb with Pre-Trained Models

---

benchmarks/experiment_configs/datasets/arxiv.json
benchmarks/experiment_configs/datasets/fmow.json
benchmarks/experiment_configs/datasets/huffpost.json
benchmarks/experiment_configs/fine-tuning-arxiv.json
benchmarks/experiment_configs/fine-tuning-fmow.json
benchmarks/experiment_configs/fine-tuning-huffpost.json
benchmarks/experiment_configs/joint-arxiv.json
benchmarks/experiment_configs/joint-fmow.json
benchmarks/experiment_configs/joint-huffpost.json
benchmarks/experiment_configs/scenarios/arxiv-16updates.json
benchmarks/experiment_configs/scenarios/clear10-10updates.json
benchmarks/experiment_configs/scenarios/clear100-11updates.json
benchmarks/experiment_configs/scenarios/fmow-16updates.json
benchmarks/experiment_configs/scenarios/huffpost-7updates.json
benchmarks/experiment_configs/scenarios/wild-time.json
benchmarks/experiment_configs/updaters/fine-tuning-arxiv.json
benchmarks/experiment_configs/updaters/fine-tuning-fmow.json
benchmarks/experiment_configs/updaters/fine-tuning-huffpost.json
benchmarks/experiment_configs/updaters/joint-arxiv.json
benchmarks/experiment_configs/updaters/joint-fmow.json
benchmarks/experiment_configs/updaters/joint-huffpost.json
benchmarks/run_benchmark.py
src/renate/benchmark/datasets/vision_datasets.py
src/renate/benchmark/datasets/wild_time_data.py
src/renate/benchmark/experiment_config.py
src/renate/benchmark/models/vision_transformer.py
test/renate/benchmark/test_experimentation_config.py

Add files required to run experimentation with Wild Time Benchmarks.
Save PIL images rather than tensors in buffers to keep memory space lower.
Found bug: `optimizer_fn` doesn't work as intended. If it exists, it must return an optimizer. We would like that it can exist but it either returns an optimizer or `None`. Currently "fixed" by adding all arguments expected for an optimizer to the function.

Wild Time Benchmarks and Small Memory Hack

---

src/renate/updaters/learner.py
src/renate/updaters/model_updater.py
test/integration_tests/configs/suites/quick/gdumb.json
test/integration_tests/configs/suites/quick/joint.json
test/renate/updaters/test_model_updater.py

Parameters stored in the Learner checkpoint were overwriting parameters of the passed model.
Numbers for Joint/GDumb are expected to change since before these methods were initialized with the weights of the previous model.

Clean Up Learner Checkpoint and Fix Model Loading

---

benchmarks/run_benchmark.py
doc/benchmarking/renate_benchmarks.rst
examples/benchmarking/class_incremental_learning_cifar10_der.py
examples/simple_classifier_cifar10/renate_config.py
examples/train_mlp_locally/renate_config.py
src/renate/benchmark/datasets/wild_time_data.py
src/renate/benchmark/experiment_config.py
src/renate/benchmark/scenarios.py
src/renate/cli/parsing_functions.py
test/dummy_datasets.py
test/integration_tests/configs/scenarios/class-incremental-2updates.json
test/integration_tests/configs/scenarios/class-incremental-5updates.json
test/renate/benchmark/test_experimentation_config.py
test/renate/benchmark/test_scenarios.py
test/renate/cli/test_parsing_functions.py
test/renate/renate_config_files/config.py
test/renate/renate_config_files/config_scenario.py

Rename `class_groupings` to `groupings` in `ClassIncrementalScenario`.
`DataIncrementalScenario` has now an argument `groupings` that allows grouping datasets similar to the `groupings` in `ClassIncrementalScenario` for classes.
Added support for training on `yearbook` with ViT.
Functionality exposed for benchmarking.

Enable Custom Grouping for DataIncrementalScenario

---

src/renate/updaters/experimental/offline_er.py
test/integration_tests/configs/suites/quick/offline-er.json

Offline ER currently uses only `batch_size` in the first model update. This PR makes it use `batch_size + memory_batch_size` to be comparable to joint training, et cetera. 

Make offline ER us total batch size in first update

---

src/renate/benchmark/models/l2p.py
src/renate/updaters/experimental/l2p.py
test/renate/benchmark/models/test_l2p.py

The previous version of L2P had the "prompting" mechanism tightly coupled. This PR separates the Prompting and the prompt selection strategy. 

Abstracting prompting transformer for use in L2P and S-Prompt

---

src/renate/memory/buffer.py
src/renate/updaters/experimental/offline_er.py
src/renate/updaters/learner.py
src/renate/utils/pytorch.py
test/integration_tests/configs/suites/quick/offline-er.json
test/renate/utils/test_pytorch.py

Offline-ER applies collate_fn individually on new and memory data. This change will apply the collate function on the entire batch instead.

Refactor Offline-ER to work with `collate_fn`

---

test/renate/benchmark/models/test_l2p.py
test/renate/benchmark/models/test_text_transformer.py
test/renate/benchmark/models/test_vision_transformer.py
test/renate/benchmark/test_experimentation_config.py
test/renate/data/test_data_module.py
test/renate/utils/test_pytorch.py

Some of the unit-tests run for a long time. The slowest one is the `test_unique_classes`. This PR simplifies this, and marks a few other long running ones (mostly ones that download HF models/datasets) with a `pytest.mark.slow` decorator. 

Speeding up unitests

---

src/renate/benchmark/datasets/vision_datasets.py
src/renate/benchmark/experiment_config.py
src/renate/utils/file.py
test/renate/benchmark/test_experimentation_config.py

Adding CDDB dataset

---

doc/benchmarking/renate_benchmarks.rst

Adds CDDB, Core50, L2P documentation on the benchmarks listing page. 

Documentation changes

---

src/renate/updaters/model_updater.py
src/renate/utils/misc.py
test/renate/utils/test_misc.py

Logging additional metrics

---

src/renate/utils/avalanche.py

Missing transformation to convert PIL images to tensors in specific cases.

Fixing Issue of Avalanche Updater with Datasets that return PIL Images

---

src/renate/updaters/avalanche/model_updater.py
src/renate/utils/avalanche.py
test/integration_tests/configs/suites/quick/avalanche-ewc.json
test/renate/utils/test_avalanche.py

To make a dataset avalanche-compatible, a special avalanche dataset was introduced. However, as part of the creation, an in-memory copy was created which causes problems with larger datasets.

Avoid In-Memory Dataset Copy for Avalanche
